### ISSUE TITLE
make build doesn't work on 3.4.11

### ISSUE THREAD

**Issue by DiegcD** [badly-drawn-wizards/vangogh_oc_fix#10]
BIOS updated to `116` when updating `SteamOS 3.4.11` and kernel `5.13.0-valve37-1-neptune` now when trying `make build` it throws this error:

`make -C /lib/modules/5.13.0-valve37-1-neptune/build CONFIG_GCC_PLUGINS=n M=/home/deck/Downloads/vangogh_oc_fix-0.0.1/module modules
make[1]: Entering directory '/usr/lib/modules/5.13.0-valve37-1-neptune/build'
make[1]: gcc: No such file or directory
  CC [M]  /home/deck/Downloads/vangogh_oc_fix-0.0.1/module/vangogh_oc_fix.o
/bin/sh: line 1: gcc: command not found
make[2]: *** [scripts/Makefile.build:272: /home/deck/Downloads/vangogh_oc_fix-0.0.1/module/vangogh_oc_fix.o] Error 127
make[1]: *** [Makefile:1847: /home/deck/Downloads/vangogh_oc_fix-0.0.1/module] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.13.0-valve37-1-neptune/build'
make: *** [Makefile:34: module/vangogh_oc_fix.ko] Error 2
`

**Comment by badly-drawn-wizards** [comment]
Do you have `gcc` installed?

**Comment by DiegcD** [comment]
> Do you have `gcc` installed?

Updating gcc fixed the issue, thank you ❤️🧡💛💚🩵💙💜
