### ISSUE TITLE
Question about building with specific kernal

### ISSUE THREAD

**Issue by theimpatientsamurai** [badly-drawn-wizards/vangogh_oc_fix#13]
I'm on a newer 6.x.x kernal, and I was able to extract the headers to the "module" folder, but when trying to build, it throws an error, saying the header isn't installed, and to "run 'sudo pacman -S -headers' to install the header. That command isn't the right format, and I can't figure out how to install the extracted headers correctly. I know you're not working on this project anymore, but any help is greatly appreciated, and would help others in the same boat as I am. Thank you so much in advance for your help!

**Comment by badly-drawn-wizards** [comment]
Apologies, it seems my script is wonkey and not showing the proper package name. It is meant to show you the specific package for your system so something like `sudo pacman -S linux-<something>-headers`.

**Comment by theimpatientsamurai** [comment]
Thank you so much for the fast response! I'm attempting an install on "6.1.52-valve9-1-neptune-61" and tried installing it with both "sudo pacman -S linux-6.1.52-valve9-headers" and "sudo pacman -S linux-6.1.52-valve9-1-neptune-61-headers" and other variations and it just doesn't seem to want to build. It's saying "could not find /lib/modules/6.1.52-valve9-1-neptune-61/build\n" you probably don't have headers installed. Run 'sudo pacman -S -headers' to install them." Stop." Not sure how to go about installing these headers now. They extracted successfully in the module/amd_headers/6.1.52-valve9 folder. Apologies for asking for more help, but this should be the last step if you're still willing to help! Again, HUGE thanks in advance!

(Worst case if I can't get it to work, I can just downgrade to overclock again)

**Comment by badly-drawn-wizards** [comment]
Ideally I'd like to find out on my steam deck the exact package to install, but unfortunately I have lent it to someone so I can't try anything. Try just plain `pacman -S linux-neptune-headers`.  If that works I'll fix the error message for future travellers. Otherwise we might have to see in the mirror.

Also, we don't have the amd headers for that version yet, so you'll need to download the linux kernel from the steamos arch mirror to extract the headers. This is only needs to be done once, and again, ideally I'd just do it and push for you, but no SteamDeck at the moment.
EDIT: Oh, you have extracted the headers, nvm

**Comment by theimpatientsamurai** [comment]
Thank you for the quick reply again! Once I'm able to try it again on my steam deck, I'll see if it works and let you know! I'll be able to test it probably tomorrow evening. Try this inside the root folder or inside the amd_headers folder?

**Comment by transguy4l80** [comment]
Following as I am having the same issue and trying to do the same thing. :D 

Let me know if I can help with anything on my end.

**Comment by theimpatientsamurai** [comment]
I tried just plain  Pacman -S linux-neptune-headers, and it just installs the 5.13 kernal. I think I'm not installing and extracting the kernal correctly, as I downloaded the "linux-neptune-61-6.1.52.valve9-1.src.tar.gz" to extract, and it attempts to download and extract it, downloads it correctly, but fails to extract. I can post the error log if needed.

Sidenote, I figured out how to downgrade to 5.13, or steam version 3.1, and although it's possible to build a version of decky to install the older powertools, it runs horribly in general in comparison, so it's not worth the downgrade. Valve really made it quite a hassle to overclock it seems, especially without the ability to prevent updates.

Another sidenote: downgrading to powertools 1.32 won't give you TDP increases, it'll increase your CPU and GPU, but you'll still be stuck at 15W max unfortunately.

**Comment by transguy4l80** [comment]
My TDP seems to work on version 116 when set in Smokeless. I am having issues with getting core speeds to set above stock. But I am about to reset bios to stock and just underclock as Valve has made it too difficult for me. Powertools is able to pull it to manually 1600 on GPU but nothing above.

**Comment by tweakbsd** [comment]
I'm running an unlocked 116 BIOS with Steam OS 3.5.7 and this kernel module built against 6.1.52-valve9 headers.  Latest PowerTools works fine with it. Sure, building this kernel module was a bit of a hassle cause of the packman issues on 3.5 but downloading the sources and extracting it to amd_headers isn't that difficult either. 

As is overclocking the deck on BIOS 116. Either use Smokeless or unlocked BIOS. Here is more info:
https://www.stanto.com/games/unlocking-the-steam-deck-bios-for-under-voltage-and-over-clocking/


I don't know what you mean by your TDP seems to work but clock speeds not. 
Do your clock speeds go above stock without PowerTools ? Cause THEY should! 

If not, you have a different problem that this kernel module won't fix. This kernel module only solves "above 3500Mhz CPU" problem when running overclock BIOS settings and wanting to use PowerTools which you need to use pt_oc.json on latest version.

**Comment by badly-drawn-wizards** [comment]
@tweakbsd if you don't mind retracing your steps here, that would be great. I can't test things myself so it would help if someone with a working setup can elaborate.

**Comment by lividhen** [comment]
gonna close this issue. If it is still relevant please re-open.
