### ISSUE TITLE
Gpu limits DO work without this fix? 

### ISSUE THREAD

**Issue by claytankozmo** [badly-drawn-wizards/vangogh_oc_fix#4]
Not really an issue, but for me gpu limits work just fine without this fix in powertools, but the CPU limits are buggy and do not work.. Are you aware of this?

**Comment by badly-drawn-wizards** [comment]
Yes. I should clarify that in the README. It is confusing. PowerTools sets the CPU limits through an interface exposed by the amdgpu kernel driver.
