### ISSUE TITLE
Exec Format Error

### ISSUE THREAD

**Issue by travistabbal** [badly-drawn-wizards/vangogh_oc_fix#7]
I am trying to use this for the current stable release. 

uname -a  
Linux steamdeck 5.13.0-valve36-1-neptune #1 SMP PREEMPT Mon, 19 Dec 2022 23:39:41 +0000 x86_64 GNU/Linux

So I downloaded linux-neptune-5.13.0.valve36-1.src.tar.gz from the link in the readme. I put it in linux-header-extract/linux-pkg. I was able to modify the makefile to get it to extract the source files needed. I also symlinked the source directory to /lib/modules/5.13.0-valve36-1-neptune/build  so the main makefile would run. 

I tried both the master branch and the 0.0.1 release. Both build now, but give me that error, which searching says I might have the wrong kernel version. I tried with and without the parameter. 

(deck@steamdeck vangogh_oc_fix-0.0.1)$ sudo modprobe vangogh_oc_fix
modprobe: ERROR: could not insert 'vangogh_oc_fix': Exec format error

I did build the main kernel tree, do I need to boot that kernel?

**Comment by travistabbal** [comment]
I managed to get it going. I did end up installing a custom build kernel, using valve's config/package source. makepkg will build the kernel (takes forever, valve compiles about everything as a module) and kernel-headers package, pacman -U then installs them. 

The default package config from valve uses a single-threaded compile. The kernel will build with multi-threaded compile. The docs for makepkg explain how to do it. I decided to let it go as I was going to sleep anyway. 

Note that there are a number of dependencies you need to install before you can build a kernel on the deck. You can probably build it on a PC if you have an Arch linux install available. 

After rebooting, I re-compiled the module and it was able to install and lets me adjust it in powertools. Watching the overlay, it is using the higher clocks now, more so when I increase TDP. It helps that the emulator allows me to reduce the GPU clocks so the CPU can use more power. 

Thanks for the code!

**Comment by badly-drawn-wizards** [comment]
Note for future users, this module intends to side step building the kernel and if you are going through that process you might as well patch it directly. [This is the line you can modify](https://github.com/torvalds/linux/blob/1639fae5132bc8a904af28d97cea0bedb3af802e/drivers/gpu/drm/amd/pm/swsmu/smu11/vangogh_ppt.c#L2101)
