### ISSUE TITLE
Kernel module updates ? 

### ISSUE THREAD

**Issue by l33tm4st3r** [badly-drawn-wizards/vangogh_oc_fix#9]
Would it be possible to precompile/generate the module for new kernels released by valve and publish them in this git ? 

Thank you.

**Comment by badly-drawn-wizards** [comment]
I would welcome a PR for this.

**Comment by lividhen** [comment]
Completed by f58409ffdba7edea6b23af3aa001515c7fbfe547 to a certain extent. If you don't like the solution please re open the issue and i will look into it more.
